project:
  type: website

website:
  title: "Ozan Evkaya"
  navbar:
    left:
      - home.qmd
      - about.qmd
      - teaching.qmd
      - research.qmd
      - Projects.qmd
      - outreach.qmd
    right:
      - contact.qmd
      - icon: github
        href: https://github.com/oevkaya
      - icon: linkedin
        href: https://www.linkedin.com/in/ozanevkaya/
      - icon: medium
        href: https://medium.com/@ozanevkaya
format:
  html:
    theme: yeti
    css: styles.css
    includes:
      in-header: |
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

editor: visual

